# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inter-display-interface.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dinter-display-interface.proto\"%\n\x0f\x44isplaySettings\x12\x12\n\nbrightness\x18\x01 \x01(\x05\"\x17\n\x06\x41nswer\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\x80\x01\n\x19InterDisplayCommunication\x12\x31\n\x12SetDisplaySettings\x12\x10.DisplaySettings\x1a\x07.Answer\"\x00\x12\x30\n\x12GetDisplaySettings\x12\x06.Empty\x1a\x10.DisplaySettings\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inter_display_interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISPLAYSETTINGS']._serialized_start=33
  _globals['_DISPLAYSETTINGS']._serialized_end=70
  _globals['_ANSWER']._serialized_start=72
  _globals['_ANSWER']._serialized_end=95
  _globals['_EMPTY']._serialized_start=97
  _globals['_EMPTY']._serialized_end=104
  _globals['_INTERDISPLAYCOMMUNICATION']._serialized_start=107
  _globals['_INTERDISPLAYCOMMUNICATION']._serialized_end=235
# @@protoc_insertion_point(module_scope)
